'use strict';
const $=s=>document.querySelector(s);
const labels={all:'All projects',restaurant:'Restaurant activity',commercial:'Commercial renovations',building:'Building activity'};
const state={feed:'all',q:'',borough:'all',period:'90',offset:0,limit:25,total:0,projects:[],savedOnly:false,selected:null};
let saved;try{saved=new Set(JSON.parse(localStorage.getItem('nyc-signals-saved')||'[]'));}catch{saved=new Set();}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shortDate=d=>d?new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Date unavailable';
const num=n=>Number(n||0).toLocaleString('en-US');
function safeUrl(url){try{const u=new URL(url);return u.protocol==='https:'&&['data.cityofnewyork.us','data.ny.gov'].includes(u.hostname)?u.href:'#';}catch{return '#';}}
function link(url,label){return `<a href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} <span class="sr-only">(opens official source in a new tab)</span><span aria-hidden="true">↗</span></a>`;}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,2800);}
function params(){const p=new URLSearchParams({feed:state.feed,q:state.q,borough:state.borough,offset:state.offset,limit:state.limit});if(state.period!=='all'){const d=new Date();d.setUTCDate(d.getUTCDate()-Number(state.period));p.set('since',d.toISOString().slice(0,10));}return p;}
async function api(path){const response=await fetch(path);if(!response.ok)throw new Error(`Request failed (${response.status}).`);return response.json();}
const bookmark='<svg viewBox="0 0 20 22" aria-hidden="true"><path d="M4 3h12v16l-6-4-6 4z"/></svg>';
function row(p){const tags=p.feeds.filter(f=>f!=='building'||p.feeds.length===1).map(f=>`<span class="tag ${f}">${esc(labels[f])}</span>`).join('');const priority=`<span class="tag priority-${esc(p.priority_band||'low')}">${esc((p.priority_band||'low').toUpperCase())} research priority</span>`;return `<article class="project-row ${state.selected===p.id?'selected':''}" data-id="${esc(p.id)}"><button class="project-open" data-open="${esc(p.id)}" aria-label="View evidence for ${esc(p.address)}"><div class="row-top"><span class="row-borough">${esc(p.borough||'Borough unavailable')}</span><time class="row-date">${shortDate(p.latest_date)}</time></div><h3 class="row-address">${esc(p.address||'Address not supplied')}</h3><p class="row-description">${esc(p.description)}</p><div class="row-bottom">${priority}${tags}<span class="evidence-count">${p.events.length} source record${p.events.length===1?'':'s'}</span><span>${esc(p.review_status)}</span></div></button><button class="save-button ${saved.has(p.id)?'saved':''}" data-save="${esc(p.id)}" aria-pressed="${saved.has(p.id)}" aria-label="${saved.has(p.id)?'Unsave':'Save'} ${esc(p.address)}">${bookmark}</button></article>`;}
let loadId=0;
async function load(){const id=++loadId;$('#project-list').setAttribute('aria-busy','true');$('#error').hidden=true;$('#empty').hidden=true;$('#results-count').textContent='Loading projects…';$('#previous').disabled=true;$('#next').disabled=true;
try{let result;
if(state.savedOnly){const all=await Promise.all([...saved].map(pid=>api('/api/projects/'+encodeURIComponent(pid)).catch(()=>null)));const q=state.q.toLowerCase();const since=params().get('since')||'';const matches=all.filter(Boolean).filter(p=>(state.feed==='all'||p.feeds.includes(state.feed))&&(state.borough==='all'||p.borough===state.borough)&&p.latest_date>=since&&(!q||JSON.stringify([p.address,p.description,p.job,p.businesses]).toLowerCase().includes(q))).sort((a,b)=>b.latest_date.localeCompare(a.latest_date));result={total:matches.length,projects:matches.slice(state.offset,state.offset+state.limit)};
}else result=await api('/api/projects?'+params());
if(id!==loadId)return;state.total=result.total;state.projects=result.projects;
$('#results-count').textContent=`${num(state.total)} ${state.savedOnly?'saved ':''}projects`;
$('#project-list').innerHTML=state.projects.map(row).join('');$('#empty').hidden=state.projects.length>0;
$('#page-label').textContent=state.total?`${state.offset+1}–${Math.min(state.offset+state.limit,state.total)} of ${num(state.total)}`:'';
$('#previous').disabled=state.offset===0;$('#next').disabled=state.offset+state.limit>=state.total;$('#export').disabled=!state.total;
if(state.projects.length && !state.projects.some(p=>p.id===state.selected))selectProject(state.projects[0]);
if(!state.projects.length){state.selected=null;$('#detail').innerHTML='<div class="detail-placeholder"><h2>Every signal has a source.</h2><p>Select a project to inspect its evidence.</p></div>';}
}catch(error){if(id!==loadId)return;$('#error-text').textContent='Could not load the local database. Check that the Python server is running, then try again.';$('#error').hidden=false;$('#results-count').textContent='Projects unavailable';$('#project-list').innerHTML='';$('#export').disabled=true;}finally{if(id===loadId)$('#project-list').setAttribute('aria-busy','false');}}
function selectProject(p){state.selected=p.id;document.querySelectorAll('.project-row').forEach(el=>el.classList.toggle('selected',el.dataset.id===p.id));
const businesses=p.businesses.length?p.businesses.map(b=>`<div class="business-line"><span>${esc(b.role)}</span>${link(b.source_url,b.name)}</div>`).join(''):'<p>No business identity supplied. No contact details have been inferred.</p>';
const property=p.property?`<section class="detail-section"><h3>Property context</h3><dl class="property-grid"><div><dt>Tax lot (BBL)</dt><dd>${esc(p.bbl)}</dd></div><div><dt>Building class</dt><dd>${esc(p.property.bldgclass||'Not supplied')}</dd></div><div><dt>Building area</dt><dd>${p.property.bldgarea?num(p.property.bldgarea)+' sq ft':'Not supplied'}</dd></div><div><dt>Year built</dt><dd>${esc(p.property.yearbuilt||'Not supplied')}</dd></div></dl><p>Property-level figures; not the area of this project. ${link(p.property.source_url,'View PLUTO record')}</p></section>`:'';
$('#detail').innerHTML=`<header class="detail-head"><div class="detail-meta"><span>${esc(p.borough)}</span><span>·</span><span>${esc(p.job||'License record')}</span></div><h2>${esc(p.address)}</h2><span class="status-badge">${esc(p.review_status)}</span><p>${esc(p.event_type)} · ${esc(p.status)}</p></header><section class="detail-section"><h3>What the record says</h3><p class="description-full">${esc(p.description)}</p></section><section class="detail-section"><h3>Why it appears in this feed</h3><ul class="reasons">${p.reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="detail-section"><h3>Recorded businesses</h3>${businesses}</section><section class="detail-section"><h3>Source history</h3><ol class="timeline">${p.events.slice(0,15).map(e=>`<li><time class="timeline-date">${shortDate(e.date)}</time><strong>${esc(e.type)}</strong><p>${esc(e.status||'Status not supplied')}${e.occupancy_filing_type?' · '+esc(e.occupancy_filing_type):''}</p>${link(e.source_url,e.source_label+' ↗')}</li>`).join('')}</ol>${p.events.length>15?`<p>${p.events.length-15} additional records included in the JSON export.</p>`:''}</section>${property}<section class="detail-section limitations"><h3>Before you act</h3><ul>${p.flags.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></section>${p.related_projects.length?`<section class="detail-section"><h3>Other records at this site</h3><p>These may be different projects or tenants. They have not been merged.</p>${p.related_projects.slice(0,5).map(id=>`<button class="related-button" data-related="${esc(id)}">${esc(id)}</button>`).join('')}</section>`:''}`;}
async function summary(){try{const s=await api('/api/summary');document.querySelector('[data-count="all"]').textContent=num(s.projects);for(const [key,count] of Object.entries(s.feeds))document.querySelector(`[data-count="${key}"]`).textContent=num(count);
const sources=Object.values(s.sources).filter(x=>x.dataset);const complete=sources.filter(x=>x.status==='ok'&&x.complete).length;$('#source-status').textContent=sources.length?`${complete}/${sources.length} sources complete for the configured window`:'No records collected yet';}catch{$('#source-status').textContent='Source status unavailable';}}
function syncSaved(){ $('#saved-count').textContent=saved.size;try{localStorage.setItem('nyc-signals-saved',JSON.stringify([...saved]));}catch{toast('Browser storage unavailable; saved items last only for this visit.');}}
document.addEventListener('click',async e=>{const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);syncSaved();if(state.savedOnly){state.offset=0;load();}else $('#project-list').innerHTML=state.projects.map(row).join('');return;}const open=e.target.closest('[data-open]');if(open){const p=state.projects.find(p=>p.id===open.dataset.open);if(p)selectProject(p);if(innerWidth<1150)$('#detail').scrollIntoView({behavior:'auto',block:'start'});return;}const related=e.target.closest('[data-related]');if(related){try{selectProject(await api('/api/projects/'+encodeURIComponent(related.dataset.related)));$('#detail').scrollIntoView({block:'start'});}catch{toast('Related project could not be loaded.');}}});
$('#feeds').addEventListener('click',e=>{const b=e.target.closest('[data-feed]');if(!b)return;state.feed=b.dataset.feed;state.offset=0;state.savedOnly=false;$('#saved-toggle').setAttribute('aria-pressed','false');$('#saved-toggle').classList.remove('active');document.querySelectorAll('[data-feed]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});$('#page-title').textContent=state.feed==='all'?'Find the next project.':labels[state.feed];load();});
$('#saved-toggle').onclick=()=>{state.savedOnly=!state.savedOnly;state.offset=0;$('#saved-toggle').setAttribute('aria-pressed',String(state.savedOnly));$('#saved-toggle').classList.toggle('active',state.savedOnly);load();};
let timer;$('#search').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{state.q=e.target.value;state.offset=0;load();},200);});
$('#borough').onchange=e=>{state.borough=e.target.value;state.offset=0;load();};$('#period').onchange=e=>{state.period=e.target.value;state.offset=0;load();};
$('#reset').onclick=()=>{clearTimeout(timer);state.q='';state.borough='all';state.period='90';state.offset=0;$('#search').value='';$('#borough').value='all';$('#period').value='90';load();};
$('#previous').onclick=()=>{state.offset=Math.max(0,state.offset-state.limit);load();};$('#next').onclick=()=>{state.offset+=state.limit;load();};$('#retry').onclick=load;
$('#export').onclick=()=>{const p=params();p.delete('limit');p.delete('offset');if(state.savedOnly)p.set('ids',[...saved].join(','));window.location.href='/api/export.csv?'+p;};
let infoInvoker;
function showInfo(html){infoInvoker=document.activeElement;$('#info-content').innerHTML=html;$('#info-panel').hidden=false;$('#info-panel').scrollIntoView({block:'start'});$('#info-panel').focus();}
$('#close-info').onclick=()=>{$('#info-panel').hidden=true;(infoInvoker&&document.contains(infoInvoker)?infoInvoker:$('#sources-button')).focus();};
$('#sources-button').onclick=async()=>{try{const s=await api('/api/sources');showInfo(`<h2>Sources & coverage</h2><p>Data is retrieved from official public sources. A complete query means the configured window was fetched; it does not mean every NYC project is covered.</p>${Object.values(s).map(v=>`<div class="source-row"><div>${link(v.url,v.name)}<small>${esc(v.dataset||'Property enrichment')}</small></div><div class="${v.status==='error'?'source-error':''}">${v.status==='error'?'Fetch failed':v.complete?'Window complete':v.coverage?'Targeted matches':'Partial collection'}<small>${num(v.fetched)} records fetched${v.source_count!=null?' / '+num(v.source_count)+' matching records':''}</small></div><div>Checked ${v.last_success?new Date(v.last_success).toLocaleString():'Not yet'}<small>${v.metadata?.rows_updated_at?'Publisher updated '+new Date(v.metadata.rows_updated_at*1000).toLocaleDateString():''}</small></div></div>`).join('')}<h3>Known gaps</h3><p>Specialist electrical, elevator and LAA datasets, legacy occupancy records, and community-board materials are outside this version. Pending licenses indicate applications, not confirmed openings. No independent contact verification has been performed.</p>`);}catch{toast('Source report unavailable. Try again.');}};
$('#quality-button').onclick=async()=>{try{const q=await api('/api/quality');showInfo(`<h2>Quality review</h2><p>Research preview. No subscription is offered until source rights, accuracy, coverage and payment onboarding have been reviewed.</p><div class="source-row"><div>${num(q.projects)} projects<small>${num(q.raw_records)} source records</small></div><div>${q.human_reviews} human reviews<small>${q.human_accuracy==null?'Accuracy not measured':(q.human_accuracy*100).toFixed(1)+'% classification accuracy'}</small></div><div>${q.agent_reviews} agent reviews<small>Agent review does not replace the human launch gate.</small></div></div>${Object.values(q.feeds).map(f=>`<h3>${esc(f.label)}</h3><p>${num(f.recent_projects)} projects with source events in the last 30 days.</p><ul>${f.gates.map(g=>`<li>${esc(g)}</li>`).join('')}</ul>`).join('')}<h3>Evaluation notes</h3><ul>${q.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`);}catch{toast('Quality report unavailable. Try again.');}};
syncSaved();summary();load();
